# 데이터 프레임 구조 파악하기 
   ### match_id 를 통해 뽑은 경기의 데이터를 보기 쉽게 정리하기
   
 ## 1. Match data
 #### 중요한 key: 소환사, 팀 , 전체 게임 데이터

## paticipants 변수 설명 
allInPings: 전체 전투 핑

assistMePings: 도와주세요 핑

assists: 어시스트 

baronKills: 바론 처치 수 

basicPings: 기본 핑

bountyLevel: 바운티 레벨 

##### challenges: 도전 과제

champExperience: 챔피언 경험치 +

champLevel: 챔피언 레벨+

championId: 챔피언 ID

championName: 챔피언 이름 +

championTransform: 챔피언 변신

commandPings: 명령 핑

consumablesPurchased: 구매한 소모품 수 +

damageDealtToBuildings: 건물에 입힌 피해량 +

damageDealtToObjectives: 목표물에 입힌 피해량 +

damageDealtToTurrets: 포탑에 입힌 피해량 +

damageSelfMitigated: 줄인 피해량

dangerPings: 위험 핑

deaths: 죽은 횟수 

doubleKills: 더블 킬

dragonKills: 드래곤 처치 수 +

eligibleForProgression: 진행 가능 여부 

enemyMissingPings: 적 실종 핑

enemyVisionPings: 적 시야 핑

firstBloodAssist: 첫 피의 어시스트 +

firstBloodKill: 첫 피의 킬 +

firstTowerAssist: 첫 타워 어시스트 +

firstTowerKill: 첫 타워 킬 +

gameEndedInEarlySurrender: 조기 항복으로 게임 종료됨 +

gameEndedInSurrender: 항복으로 게임 종료됨 +

getBackPings: 후퇴 핑 

goldEarned: 획득한 골드 +

goldSpent: 소비한 골드

holdPings: 방어 핑

individualPosition: 개별 포지션 +

inhibitorKills: 억제기 처치 수 +

inhibitorTakedowns: 억제기 타켓

inhibitorsLost: 잃은 억제기

item1: 아이템 1

item2: 아이템 2

item3: 아이템 3

item4: 아이템 4

item5: 아이템 5


item6: 아이템 6

itemsPurchased: 구매한 아이템 수

killingSprees: 킬 스프리

kills: 킬 수

lane: 라인 +

largestCriticalStrike: 가장 큰 치명타 피해

largestKillingSpree: 가장 큰 킬 스프리


largestMultiKill: 가장 큰 다중 킬

longestTimeSpentLiving: 최대 생존 시간



magicDamageDealt: 마법 피해량

magicDamageDealtToChampions: 챔피언에게 입힌 마법 피해량

magicDamageTaken: 받은 마법 피해량

##### missions: 미션

needVisionPings: 시야 필요 핑

nexusKills: 넥서스 처치 수

nexusLost: 잃은 넥서스 수

nexusTakedowns: 넥서스 타켓

objectivesStolen: 목표물 훔침

objectivesStolenAssists: 목표물 훔침 어시스트

onMyWayPings: 가는 중 핑

participantId: 참가자 ID

pentaKills: 펜타 킬

##### perks: 퍼크 (룬 , 마스터리)  +

physicalDamageDealt: 물리 피해량

physicalDamageDealtToChampions: 챔피언에게 입힌 물리 피해량

physicalDamageTaken: 받은 물리 피해량

placement: 순위

playerAugment1: 플레이어 강화 1

playerAugment2: 플레이어 강화 2

playerAugment3: 플레이어 강화 3

playerAugment4: 플레이어 강화 4

playerScore0: 플레이어 점수 0

playerScore1: 플레이어 점수 1

playerScore11: 플레이어 점수 11

playerScore2: 플레이어 점수 2

playerScore3: 플레이어 점수 3

playerScore4: 플레이어 점수 4

playerScore5: 플레이어 점수 5

playerScore6: 플레이어 점수 6

playerScore7: 플레이어 점수 7

playerScore8: 플레이어 점수 8

playerScore9: 플레이어 점수 9

playerSubteamId: 플레이어 하위 팀 ID

profileIcon: 프로필 아이콘

pushPings: 밀기 핑

puuid: PUUID

quadraKills: 쿼드라 킬

riotIdGameName: Riot ID 게임 이름

riotIdTagline: Riot ID 태그라인

role: 역할 +

sightWardsBoughtInGame: 시야 와드 구매 수

spell1Casts: 스펠 1 시전 횟수

spell3Casts: 스펠 3 시전 횟수

spell4Casts: 스펠 4 시전 횟수

subteamPlacement: 서브팀 순위

summoner1Casts: 소환사 주문 1 시전 횟수

summoner1Id: 소환사 주문 1 ID

summoner2Casts: 소환사 주문 2 시전 횟수

summoner2Id: 소환사 주문 2 ID

summonerId: 소환사 ID

summonerLevel: 소환사 레벨

summonerName: 소환사 이름

teamEarlySurrendered: 팀 조기 항복 여부 +

teamId: 팀 ID

teamPosition: 팀 포지션 +

timeCCingOthers: 다른 플레이어 CC 시간

timePlayed: 플레이 시간

totalAllyJungleMinionsKilled: 아군 정글 미니언 처치 수

totalDamageDealt: 총 피해량

totalDamageDealtToChampions: 챔피언에게 입힌 총 피해량

totalDamageShieldedOnTeammates: 팀원들에게 보호한 총 피해량

totalEnemyJungleMinionsKilled: 적 측 정글 미니언 처치 수

totalHeal: 총 치유량

totalHealsOnTeammates: 팀원들에게 한 총 치유량


totalMinionsKilled: 총 미니언 처치 수


totalTimeCCDealt: 총 CC 딜링 시간

totalTimeSpentDead: 총 사망 시간

totalUnitsHealed: 총 치유한 유닛 수

tripleKills: 트리플 킬

trueDamageDealt: 진정한 피해량

trueDamageDealtToChampions: 챔피언에게 입힌 진정한 피해량

trueDamageTaken: 받은 진정한 피해량

turretKills: 포탑 처치 수

turretTakedowns: 포탑 타켓

turretsLost: 잃은 포탑 수


unrealKills: 언리얼 킬

visionClearedPings: 시야 제거 핑

visionScore: 시야 점수

visionWardsBoughtInGame: 게임 중 구매한 시야 와드 수

wardsKilled: 파괴한 와드 수


wardsPlaced: 설치한 와드 수

win: 승리 여부 +

In [1]:
#라이브러리 import 하기 

import requests
from urllib import parse
import pprint
pp = pprint.PrettyPrinter(indent=4)
import pandas as pd
import time

In [2]:
# json 타입의 데이터 가져오기 
r = requests.get('https://asia.api.riotgames.com/lol/match/v5/matches/KR_6965278983?api_key=RGAPI-c33dbe68-ba64-4996-8a8c-37c7cfd572a0')

In [3]:
#해당 json 파일을 데이터 프레임 형식으로 바꾸기 
df=pd.DataFrame(r.json())

In [4]:
df

,metadata,info
dataVersion,2,NaN
matchId,KR_6965278983,NaN
participants,[0MDFTfbC7PqLFggO5qmHqZjUKB2NeL1L3rXRILrdc8M_v...,"[{'allInPings': 0, 'assistMePings': 0, 'assist..."
endOfGameResult,NaN,GameComplete
gameCreation,NaN,1708890065287
gameDuration,NaN,1927
gameEndTimestamp,NaN,1708892054463
gameId,NaN,6965278983
gameMode,NaN,CLASSIC
gameName,NaN,teambuilder-match-6965278983
gameStartTimestamp,NaN,1708890127100
gameType,NaN,MATCHED_GAME
gameVersion,NaN,14.4.562.1960
mapId,NaN,11
platformId,NaN,KR
queueId,NaN,420
teams,NaN,"[{'bans': [{'championId': 143, 'pickTurn': 1},..."
tournamentCode,NaN,

### 1.게임에 대한 정보

In [6]:
# 게임 자체에 대한 정보 
game_info=pd.DataFrame(df['info'][3:15])
game_info

                                            info
endOfGameResult                     GameComplete
gameCreation                       1708890065287
gameDuration                                1927
gameEndTimestamp                   1708892054463
gameId                                6965278983
gameMode                                 CLASSIC
gameName            teambuilder-match-6965278983
gameStartTimestamp                 1708890127100
gameType                            MATCHED_GAME
gameVersion                        14.4.562.1960
mapId                                         11
platformId                                    KR

### 2. 경기 참여한 사람에 대한 정보

In [7]:
## 경기에 참여하는 참여자 10명의 코드
participants_code=df['metadata']['participants']

In [8]:
#경기에 참여한 소환사의 데이터 (10명)

participants_data = df['info']['participants']
participants_df = pd.DataFrame(participants_data)
participants_df

,allInPings,assistMePings,assists,baronKills,basicPings,bountyLevel,challenges,champExperience,champLevel,championId,...,turretKills,turretTakedowns,turretsLost,unrealKills,visionClearedPings,visionScore,visionWardsBoughtInGame,wardsKilled,wardsPlaced,win
0,0,0,5,0,0,1,"{'12AssistStreakCount': 0, 'abilityUses': 160,...",18494,18,17,...,4,5,7,0,0,31,2,8,8,True
1,0,4,3,2,0,1,"{'12AssistStreakCount': 0, 'abilityUses': 261,...",19821,18,245,...,1,1,7,0,0,20,0,3,6,True
2,0,0,5,0,0,0,"{'12AssistStreakCount': 0, 'abilityUses': 96, ...",15836,16,18,...,3,3,7,0,0,20,3,1,8,True
3,0,8,6,0,0,3,"{'12AssistStreakCount': 0, 'abilityUses': 212,...",19338,18,895,...,3,5,7,0,0,18,0,0,11,True
4,0,7,17,0,0,1,"{'12AssistStreakCount': 0, 'abilityUses': 126,...",17987,17,57,...,0,1,7,0,0,70,5,13,29,True
5,0,0,9,0,0,0,"{'12AssistStreakCount': 0, 'abilityUses': 448,...",17255,17,13,...,2,3,11,0,0,13,2,0,2,False
6,0,1,5,0,0,0,"{'12AssistStreakCount': 0, 'abilityUses': 566,...",12882,14,64,...,1,1,11,0,0,40,12,4,17,False
7,0,1,7,0,0,1,"{'12AssistStreakCount': 0, 'abilityUses': 322,...",20574,18,4,...,2,2,11,0,0,27,4,4,13,False
8,0,0,4,0,0,0,"{'12AssistStreakCount': 0, 'abilityUses': 403,...",14144,15,81,...,2,2,11,0,0,7,1,4,3,False
9,1,7,15,0,0,0,"{'12AssistStreakCount': 1, 'abilityUses': 339,...",11841,14,43,...,0,0,11,0,0,90,10,15,45,False

In [9]:
# 칼럼 내용확인하기 
participants_df.columns[0:20]

Index(['allInPings', 'assistMePings', 'assists', 'baronKills', 'basicPings',
       'bountyLevel', 'challenges', 'champExperience', 'champLevel',
       'championId', 'championName', 'championTransform', 'commandPings',
       'consumablesPurchased', 'damageDealtToBuildings',
       'damageDealtToObjectives', 'damageDealtToTurrets',
       'damageSelfMitigated', 'dangerPings', 'deaths'],
      dtype='object')

In [10]:
participants_df.columns[21:40]

Index(['doubleKills', 'dragonKills', 'eligibleForProgression',
       'enemyMissingPings', 'enemyVisionPings', 'firstBloodAssist',
       'firstBloodKill', 'firstTowerAssist', 'firstTowerKill',
       'gameEndedInEarlySurrender', 'gameEndedInSurrender', 'getBackPings',
       'goldEarned', 'goldSpent', 'holdPings', 'individualPosition',
       'inhibitorKills', 'inhibitorTakedowns', 'inhibitorsLost'],
      dtype='object')

In [11]:
participants_df.columns[41:60]

Index(['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'itemsPurchased',
       'killingSprees', 'kills', 'lane', 'largestCriticalStrike',
       'largestKillingSpree', 'largestMultiKill', 'longestTimeSpentLiving',
       'magicDamageDealt', 'magicDamageDealtToChampions', 'magicDamageTaken',
       'missions', 'needVisionPings'],
      dtype='object')

In [12]:
participants_df.columns[61:80]

Index(['nexusKills', 'nexusLost', 'nexusTakedowns', 'objectivesStolen',
       'objectivesStolenAssists', 'onMyWayPings', 'participantId',
       'pentaKills', 'perks', 'physicalDamageDealt',
       'physicalDamageDealtToChampions', 'physicalDamageTaken', 'placement',
       'playerAugment1', 'playerAugment2', 'playerAugment3', 'playerAugment4',
       'playerScore0', 'playerScore1'],
      dtype='object')

In [93]:
participants_df.columns[81:100]

Index(['playerScore11', 'playerScore2', 'playerScore3', 'playerScore4',
       'playerScore5', 'playerScore6', 'playerScore7', 'playerScore8',
       'playerScore9', 'playerSubteamId', 'profileIcon', 'pushPings', 'puuid',
       'quadraKills', 'riotIdGameName', 'riotIdTagline', 'role',
       'sightWardsBoughtInGame', 'spell1Casts'],
      dtype='object')

In [94]:
participants_df.columns[101:120]

Index(['spell3Casts', 'spell4Casts', 'subteamPlacement', 'summoner1Casts',
       'summoner1Id', 'summoner2Casts', 'summoner2Id', 'summonerId',
       'summonerLevel', 'summonerName', 'teamEarlySurrendered', 'teamId',
       'teamPosition', 'timeCCingOthers', 'timePlayed',
       'totalAllyJungleMinionsKilled', 'totalDamageDealt',
       'totalDamageDealtToChampions', 'totalDamageShieldedOnTeammates'],
      dtype='object')

In [95]:
participants_df.columns[121:142]

Index(['totalEnemyJungleMinionsKilled', 'totalHeal', 'totalHealsOnTeammates',
       'totalMinionsKilled', 'totalTimeCCDealt', 'totalTimeSpentDead',
       'totalUnitsHealed', 'tripleKills', 'trueDamageDealt',
       'trueDamageDealtToChampions', 'trueDamageTaken', 'turretKills',
       'turretTakedowns', 'turretsLost', 'unrealKills', 'visionClearedPings',
       'visionScore', 'visionWardsBoughtInGame', 'wardsKilled', 'wardsPlaced',
       'win'],
      dtype='object')

In [10]:
# 소환사에 대한 데이터 프레임의 열이 142개임 
participants_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Columns: 142 entries, allInPings to win
dtypes: bool(9), int64(120), object(13)
memory usage: 10.6+ KB

### 2-1. 딕셔너리가 있는 칼럼들

In [11]:
object_columns = participants_df.select_dtypes(include=['object'])
object_columns

,challenges,championName,individualPosition,lane,missions,perks,puuid,riotIdGameName,riotIdTagline,role,summonerId,summonerName,teamPosition
0,"{'12AssistStreakCount': 0, 'abilityUses': 160,...",Teemo,TOP,JUNGLE,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",0MDFTfbC7PqLFggO5qmHqZjUKB2NeL1L3rXRILrdc8M_vt...,제너럴 모,KR1,NONE,LhG7H7NLXxsstNpGS5e1ll3rHoVgwl-q57NiCwqLlmYl8qk,제너럴 모,TOP
1,"{'12AssistStreakCount': 0, 'abilityUses': 261,...",Ekko,JUNGLE,JUNGLE,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",lDht_007ZxL4yBnCyrc4-pHTIS0EfZPXxN9hh9GyP323zv...,병1269기 김준영,KR1,NONE,JVG4wyGjEmdjZgTy0reYYLZmDv9Rv1iXivzU5yyuevdH5ug,병1269기 김준영,JUNGLE
2,"{'12AssistStreakCount': 0, 'abilityUses': 96, ...",Tristana,MIDDLE,MIDDLE,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",-ejPOUV53shLiuqyWyYAfyiiFNViYQ6WjLgMLA_tkQWg8-...,01년생황석민,KR1,CARRY,NdzK_Z9hl2t6DsadgB83LBTqtazCD2gUwhdURGE-TOassfQ,01년생황석민,MIDDLE
3,"{'12AssistStreakCount': 0, 'abilityUses': 212,...",Nilah,BOTTOM,BOTTOM,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",rogckr1Am6L6wdkwlAVVTFRThz4Z8DfNgf4Pb0xZJUZeWD...,박지호,wlgh,SOLO,Dcm-RX_g6bgGMi-Dk737onG0c8bjejtHXydpVDz-P3mYvcE,김희정따까리,BOTTOM
4,"{'12AssistStreakCount': 0, 'abilityUses': 126,...",Maokai,UTILITY,MIDDLE,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5010, ...",8HZM-1Zn7FDPE2H_7XHA7li_gKL5H7ySL00iz2O16Dv4pD...,동서울 물방망이,KR1,SUPPORT,DSv9VvE46SuB06X098jQvExo44CeI2x6K2icgVFZ9zCol_k,동서울 물방망이,UTILITY
5,"{'12AssistStreakCount': 0, 'abilityUses': 448,...",Ryze,TOP,TOP,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5011, 'flex': 5008, ...",p3kiCH5UNcTcjhfzx4LbApKBFLe_o_NZ_d7xz31-MeIRve...,헤드한대,강건파,SOLO,aXVc4tZuGZ_sf87nQyudakl-jkcW4aPHSs46Vr9I2GFCB0s,서폿갈 여친구함,TOP
6,"{'12AssistStreakCount': 0, 'abilityUses': 566,...",LeeSin,JUNGLE,JUNGLE,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",6CdIoMJMaG-62FA0AOtEolZUetPkQBd_nI1F3kF9gOaDwD...,ni ma zai nar,KR1,NONE,dwVlHwNirDzyr2NwZi36OUF5mMzzNYD7jHg5sezxM08GAo3t,ni ma zai nar,JUNGLE
7,"{'12AssistStreakCount': 0, 'abilityUses': 322,...",TwistedFate,MIDDLE,MIDDLE,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",OCgih0WQysqgKDGN8bgBUHZjMNLiz04EWQzJ1oLBIxiilH...,오즈메이커,KR1,SOLO,_kCA1mdCak7leTY2MlyOUDHZb11L9nFs3TFGuuWsQSd4FFg,오즈메이커,MIDDLE
8,"{'12AssistStreakCount': 0, 'abilityUses': 403,...",Ezreal,BOTTOM,BOTTOM,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",nj_31R9tg_JbAImcNRUkWPPbMZ6smsTBajKk1XpvueH_56...,이즈의꿈,KR1,CARRY,I7hdVPy53KDCo3RdvlYKdWP0G_uVooY1IuDlcRbLvfnU5Q,이즈의꿈,BOTTOM
9,"{'12AssistStreakCount': 1, 'abilityUses': 339,...",Karma,UTILITY,BOTTOM,"{'playerScore0': 0, 'playerScore1': 0, 'player...","{'statPerks': {'defense': 5001, 'flex': 5008, ...",KDkK0bNvrkZl3WIpkOETvP7c9MITT0aaQppNJpQ-2_q4LG...,아트의꿈,KR1,SUPPORT,37I5Em-ahJAdd0A9Hj_93JHsiwIvtM_mpOA7JJ4EKbpHzA,아트의꿈,UTILITY

In [12]:
#challenges 안에 있는 키 확인하기 
participants_df['challenges'][0].keys()

dict_keys(['12AssistStreakCount', 'abilityUses', 'acesBefore15Minutes', 'alliedJungleMonsterKills', 'baronBuffGoldAdvantageOverThreshold', 'baronTakedowns', 'blastConeOppositeOpponentCount', 'bountyGold', 'buffsStolen', 'completeSupportQuestInTime', 'controlWardTimeCoverageInRiverOrEnemyHalf', 'controlWardsPlaced', 'damagePerMinute', 'damageTakenOnTeamPercentage', 'dancedWithRiftHerald', 'deathsByEnemyChamps', 'dodgeSkillShotsSmallWindow', 'doubleAces', 'dragonTakedowns', 'earliestBaron', 'earliestDragonTakedown', 'earlyLaningPhaseGoldExpAdvantage', 'effectiveHealAndShielding', 'elderDragonKillsWithOpposingSoul', 'elderDragonMultikills', 'enemyChampionImmobilizations', 'enemyJungleMonsterKills', 'epicMonsterKillsNearEnemyJungler', 'epicMonsterKillsWithin30SecondsOfSpawn', 'epicMonsterSteals', 'epicMonsterStolenWithoutSmite', 'firstTurretKilled', 'flawlessAces', 'fullTeamTakedown', 'gameLength', 'getTakedownsInAllLanesEarlyJungleAsLaner', 'goldPerMinute', 'hadOpenNexus', 'immobilizeAndKillWithAlly', 'initialBuffCount', 'initialCrabCount', 'jungleCsBefore10Minutes', 'junglerTakedownsNearDamagedEpicMonster', 'kTurretsDestroyedBeforePlatesFall', 'kda', 'killAfterHiddenWithAlly', 'killParticipation', 'killedChampTookFullTeamDamageSurvived', 'killingSprees', 'killsNearEnemyTurret', 'killsOnOtherLanesEarlyJungleAsLaner', 'killsOnRecentlyHealedByAramPack', 'killsUnderOwnTurret', 'killsWithHelpFromEpicMonster', 'knockEnemyIntoTeamAndKill', 'landSkillShotsEarlyGame', 'laneMinionsFirst10Minutes', 'laningPhaseGoldExpAdvantage', 'legendaryCount', 'legendaryItemUsed', 'lostAnInhibitor', 'maxCsAdvantageOnLaneOpponent', 'maxKillDeficit', 'maxLevelLeadLaneOpponent', 'mejaisFullStackInTime', 'moreEnemyJungleThanOpponent', 'multiKillOneSpell', 'multiTurretRiftHeraldCount', 'multikills', 'multikillsAfterAggressiveFlash', 'outerTurretExecutesBefore10Minutes', 'outnumberedKills', 'outnumberedNexusKill', 'perfectDragonSoulsTaken', 'perfectGame', 'pickKillWithAlly', 'playedChampSelectPosition', 'poroExplosions', 'quickCleanse', 'quickFirstTurret', 'quickSoloKills', 'riftHeraldTakedowns', 'saveAllyFromDeath', 'scuttleCrabKills', 'skillshotsDodged', 'skillshotsHit', 'snowballsHit', 'soloBaronKills', 'soloKills', 'soloTurretsLategame', 'stealthWardsPlaced', 'survivedSingleDigitHpCount', 'survivedThreeImmobilizesInFight', 'takedownOnFirstTurret', 'takedowns', 'takedownsAfterGainingLevelAdvantage', 'takedownsBeforeJungleMinionSpawn', 'takedownsFirstXMinutes', 'takedownsInAlcove', 'takedownsInEnemyFountain', 'teamBaronKills', 'teamDamagePercentage', 'teamElderDragonKills', 'teamRiftHeraldKills', 'tookLargeDamageSurvived', 'turretPlatesTaken', 'turretTakedowns', 'turretsTakenWithRiftHerald', 'twentyMinionsIn3SecondsCount', 'twoWardsOneSweeperCount', 'unseenRecalls', 'visionScoreAdvantageLaneOpponent', 'visionScorePerMinute', 'wardTakedowns', 'wardTakedownsBefore20M', 'wardsGuarded'])

In [145]:
pd.DataFrame(participants_df['challenges'][0])

,12AssistStreakCount,abilityUses,acesBefore15Minutes,alliedJungleMonsterKills,baronTakedowns,blastConeOppositeOpponentCount,bountyGold,buffsStolen,completeSupportQuestInTime,controlWardsPlaced,...,turretTakedowns,turretsTakenWithRiftHerald,twentyMinionsIn3SecondsCount,twoWardsOneSweeperCount,unseenRecalls,visionScoreAdvantageLaneOpponent,visionScorePerMinute,wardTakedowns,wardTakedownsBefore20M,wardsGuarded
0,0,322,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0.339732,0.752054,1,1,0
1,0,322,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0.339732,0.752054,1,1,0

In [28]:
# 룬 및 마스터리 시스템에 대한 열 
participants_df['perks'][0]

{'statPerks': {'defense': 5011, 'flex': 5008, 'offense': 5008},
 'styles': [{'description': 'primaryStyle',
   'selections': [{'perk': 8010, 'var1': 75, 'var2': 0, 'var3': 0},
    {'perk': 8009, 'var1': 2132, 'var2': 0, 'var3': 0},
    {'perk': 9104, 'var1': 12, 'var2': 20, 'var3': 0},
    {'perk': 8299, 'var1': 399, 'var2': 0, 'var3': 0}],
   'style': 8000},
  {'description': 'subStyle',
   'selections': [{'perk': 8345, 'var1': 3, 'var2': 0, 'var3': 0},
    {'perk': 8304, 'var1': 9, 'var2': 4, 'var3': 5}],
   'style': 8300}]}

In [23]:
# 모든 플레이러에게 0 점임 
participants_df['missions'][0]

{'playerScore0': 0,
 'playerScore1': 0,
 'playerScore10': 0,
 'playerScore11': 0,
 'playerScore2': 0,
 'playerScore3': 0,
 'playerScore4': 0,
 'playerScore5': 0,
 'playerScore6': 0,
 'playerScore7': 0,
 'playerScore8': 0,
 'playerScore9': 0}

In [103]:
participants_df['challenges'][0]

{'12AssistStreakCount': 0,
 'abilityUses': 322,
 'acesBefore15Minutes': 0,
 'alliedJungleMonsterKills': 0,
 'baronTakedowns': 0,
 'blastConeOppositeOpponentCount': 0,
 'bountyGold': 0,
 'buffsStolen': 0,
 'completeSupportQuestInTime': 0,
 'controlWardsPlaced': 0,
 'damagePerMinute': 783.2646649845939,
 'damageTakenOnTeamPercentage': 0.22189706507268223,
 'dancedWithRiftHerald': 0,
 'deathsByEnemyChamps': 3,
 'dodgeSkillShotsSmallWindow': 2,
 'doubleAces': 0,
 'dragonTakedowns': 0,
 'earlyLaningPhaseGoldExpAdvantage': 0,
 'effectiveHealAndShielding': 0,
 'elderDragonKillsWithOpposingSoul': 0,
 'elderDragonMultikills': 0,
 'enemyChampionImmobilizations': 40,
 'enemyJungleMonsterKills': 0,
 'epicMonsterKillsNearEnemyJungler': 0,
 'epicMonsterKillsWithin30SecondsOfSpawn': 0,
 'epicMonsterSteals': 0,
 'epicMonsterStolenWithoutSmite': 0,
 'firstTurretKilled': 0,
 'flawlessAces': 0,
 'fullTeamTakedown': 0,
 'gameLength': 1217.7884273,
 'getTakedownsInAllLanesEarlyJungleAsLaner': 0,
 'goldPerMinute': 443.15945284644437,
 'hadOpenNexus': 0,
 'highestChampionDamage': 1,
 'immobilizeAndKillWithAlly': 3,
 'initialBuffCount': 0,
 'initialCrabCount': 0,
 'jungleCsBefore10Minutes': 0,
 'junglerTakedownsNearDamagedEpicMonster': 0,
 'kTurretsDestroyedBeforePlatesFall': 0,
 'kda': 3,
 'killAfterHiddenWithAlly': 0,
 'killParticipation': 0.375,
 'killedChampTookFullTeamDamageSurvived': 0,
 'killingSprees': 1,
 'killsNearEnemyTurret': 1,
 'killsOnOtherLanesEarlyJungleAsLaner': 0,
 'killsOnRecentlyHealedByAramPack': 0,
 'killsUnderOwnTurret': 1,
 'killsWithHelpFromEpicMonster': 0,
 'knockEnemyIntoTeamAndKill': 3,
 'landSkillShotsEarlyGame': 4,
 'laneMinionsFirst10Minutes': 68,
 'laningPhaseGoldExpAdvantage': 0,
 'legendaryCount': 0,
 'legendaryItemUsed': [3142, 3004],
 'lostAnInhibitor': 0,
 'maxCsAdvantageOnLaneOpponent': 23,
 'maxKillDeficit': 1,
 'maxLevelLeadLaneOpponent': 2,
 'mejaisFullStackInTime': 0,
 'moreEnemyJungleThanOpponent': 0,
 'multiKillOneSpell': 0,
 'multiTurretRiftHeraldCount': 0,
 'multikills': 1,
 'multikillsAfterAggressiveFlash': 1,
 'outerTurretExecutesBefore10Minutes': 0,
 'outnumberedKills': 1,
 'outnumberedNexusKill': 0,
 'perfectDragonSoulsTaken': 0,
 'perfectGame': 0,
 'pickKillWithAlly': 6,
 'playedChampSelectPosition': 1,
 'poroExplosions': 0,
 'quickCleanse': 0,
 'quickFirstTurret': 0,
 'quickSoloKills': 0,
 'riftHeraldTakedowns': 0,
 'saveAllyFromDeath': 0,
 'scuttleCrabKills': 0,
 'skillshotsDodged': 64,
 'skillshotsHit': 15,
 'snowballsHit': 0,
 'soloBaronKills': 0,
 'soloKills': 3,
 'stealthWardsPlaced': 7,
 'survivedSingleDigitHpCount': 0,
 'survivedThreeImmobilizesInFight': 0,
 'takedownOnFirstTurret': 0,
 'takedowns': 9,
 'takedownsAfterGainingLevelAdvantage': 0,
 'takedownsBeforeJungleMinionSpawn': 0,
 'takedownsFirstXMinutes': 6,
 'takedownsInAlcove': 0,
 'takedownsInEnemyFountain': 0,
 'teamBaronKills': 0,
 'teamDamagePercentage': 0.2821861416616796,
 'teamElderDragonKills': 0,
 'teamRiftHeraldKills': 1,
 'teleportTakedowns': 1,
 'tookLargeDamageSurvived': 0,
 'turretPlatesTaken': 3,
 'turretTakedowns': 0,
 'turretsTakenWithRiftHerald': 5,
 'twentyMinionsIn3SecondsCount': 0,
 'twoWardsOneSweeperCount': 0,
 'unseenRecalls': 0,
 'visionScoreAdvantageLaneOpponent': 0.33973217010498047,
 'visionScorePerMinute': 0.7520535999392577,
 'wardTakedowns': 1,
 'wardTakedownsBefore20M': 1,
 'wardsGuarded': 0}

In [60]:
participants_df.columns

Index(['allInPings', 'assistMePings', 'assists', 'baronKills', 'basicPings',
       'bountyLevel', 'challenges', 'champExperience', 'champLevel',
       'championId',
       ...
       'turretKills', 'turretTakedowns', 'turretsLost', 'unrealKills',
       'visionClearedPings', 'visionScore', 'visionWardsBoughtInGame',
       'wardsKilled', 'wardsPlaced', 'win'],
      dtype='object', length=142)

In [27]:
participants_df['individualPosition']

0        TOP
1     JUNGLE
2     MIDDLE
3     BOTTOM
4    UTILITY
5        TOP
6     JUNGLE
7     MIDDLE
8     BOTTOM
9    UTILITY
Name: individualPosition, dtype: object

In [25]:
participants_df['teamPosition']

0        TOP
1     JUNGLE
2     MIDDLE
3     BOTTOM
4    UTILITY
5        TOP
6     JUNGLE
7     MIDDLE
8     BOTTOM
9    UTILITY
Name: teamPosition, dtype: object

### 3. 팀에 대한 정보

In [76]:
teams_df=pd.DataFrame(df['info']['teams'])
teams_df

,bans,objectives,teamId,win
0,"[{'championId': 901, 'pickTurn': 1}, {'champio...","{'baron': {'first': False, 'kills': 0}, 'champ...",100,True
1,"[{'championId': 103, 'pickTurn': 6}, {'champio...","{'baron': {'first': False, 'kills': 0}, 'champ...",200,False

In [80]:
#이긴 팀 밴픽 정보 
# 밴한 챔피언 정보 
teams_df.iloc[0]['bans']

[{'championId': 901, 'pickTurn': 1},
 {'championId': 910, 'pickTurn': 2},
 {'championId': 57, 'pickTurn': 3},
 {'championId': 106, 'pickTurn': 4},
 {'championId': -1, 'pickTurn': 5}]

In [81]:
#이긴 팀 오브젝트에 대한 정보 
# 퍼스트에 대한 정보와 킬수에 대한 정보 
teams_df.iloc[0]['objectives']

{'baron': {'first': False, 'kills': 0},
 'champion': {'first': True, 'kills': 24},
 'dragon': {'first': True, 'kills': 3},
 'horde': {'first': True, 'kills': 6},
 'inhibitor': {'first': False, 'kills': 0},
 'riftHerald': {'first': True, 'kills': 1},
 'tower': {'first': False, 'kills': 4}}

# 2. 타임라인 데이터 
### 타임라인 데이터에서는 participants , frames 데이터가 중요 
### 게임 시간을 timestamp 를 통해 나타냄

In [5]:
r1=requests.get('https://asia.api.riotgames.com/lol/match/v5/matches/KR_6965278983/timeline?api_key=RGAPI-c33dbe68-ba64-4996-8a8c-37c7cfd572a0')

In [8]:
r1.json()['info'].keys()

dict_keys(['endOfGameResult', 'frameInterval', 'frames', 'gameId', 'participants'])

In [119]:
df2=pd.DataFrame(r1.json())

In [15]:
#타임라인 데이터를 데이터프레임으로 나타내기 
df2

,metadata,info
dataVersion,2,NaN
matchId,KR_6965278983,NaN
participants,[0MDFTfbC7PqLFggO5qmHqZjUKB2NeL1L3rXRILrdc8M_v...,"[{'participantId': 1, 'puuid': '0MDFTfbC7PqLFg..."
endOfGameResult,NaN,GameComplete
frameInterval,NaN,60000
frames,NaN,"[{'events': [{'realTimestamp': 1708890127026, ..."
gameId,NaN,6965278983

In [16]:
df2['info']

dataVersion                                                      NaN
matchId                                                          NaN
participants       [{'participantId': 1, 'puuid': '0MDFTfbC7PqLFg...
endOfGameResult                                         GameComplete
frameInterval                                                  60000
frames             [{'events': [{'realTimestamp': 1708890127026, ...
gameId                                                    6965278983
Name: info, dtype: object

## 1. Frames 데이터 살펴보기 
### events , participantFrames, timestamp 세 개로 구성됨

In [17]:
# frames 데이터에는 events, participants, timstamp 키가 존재한다 
df2['info']['frames'][0].keys()

dict_keys(['events', 'participantFrames', 'timestamp'])

## 게임 시간을 timestamp 열을 통해서 나타낸다 
#### 총 33분 게임이므로 1분마다의 event 와 participants에 대한 내용을 담은 행이 33개임을 확인할 수 있다.

In [162]:
# 60000  => 1분 단위 33분 게임 
df3=pd.DataFrame(df2['info']['frames'])
df3

,events,participantFrames,timestamp
0,"[{'realTimestamp': 1708890127026, 'timestamp':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",0
1,"[{'itemId': 3865, 'participantId': 10, 'timest...","{'1': {'championStats': {'abilityHaste': 0, 'a...",60032
2,"[{'levelUpType': 'NORMAL', 'participantId': 4,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",120039
3,"[{'itemId': 2003, 'participantId': 5, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",180041
4,"[{'assistingParticipantIds': [6], 'bounty': 30...","{'1': {'championStats': {'abilityHaste': 0, 'a...",240050
5,"[{'itemId': 2003, 'participantId': 1, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",300064
6,"[{'levelUpType': 'NORMAL', 'participantId': 10...","{'1': {'championStats': {'abilityHaste': 0, 'a...",360075
7,"[{'levelUpType': 'NORMAL', 'participantId': 9,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",420121
8,"[{'itemId': 2003, 'participantId': 8, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",480143
9,"[{'itemId': 1043, 'participantId': 1, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",540148
10,"[{'itemId': 1052, 'participantId': 10, 'timest...","{'1': {'championStats': {'abilityHaste': 0, 'a...",600162
11,"[{'creatorId': 10, 'timestamp': 600261, 'type'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",660185
12,"[{'itemId': 1052, 'participantId': 10, 'timest...","{'1': {'championStats': {'abilityHaste': 0, 'a...",720195
13,"[{'killerId': 10, 'timestamp': 720329, 'type':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",780199
14,"[{'level': 11, 'participantId': 8, 'timestamp'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",840217
15,"[{'actualStartTime': 855000, 'teamId': 100, 't...","{'1': {'championStats': {'abilityHaste': 0, 'a...",900237
16,"[{'itemId': 1001, 'participantId': 3, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",960262
17,"[{'afterId': 0, 'beforeId': 3003, 'goldGain': ...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1020284
18,"[{'levelUpType': 'NORMAL', 'participantId': 8,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1080313
19,"[{'level': 10, 'participantId': 1, 'timestamp'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1140325
20,"[{'itemId': 1026, 'participantId': 1, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1200352
21,"[{'itemId': 1052, 'participantId': 2, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1260363
22,"[{'levelUpType': 'NORMAL', 'participantId': 1,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1320380
23,"[{'level': 13, 'participantId': 5, 'timestamp'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1380393
24,"[{'creatorId': 1, 'timestamp': 1381433, 'type'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1440419
25,"[{'killerId': 5, 'timestamp': 1441087, 'type':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1500439
26,"[{'itemId': 2055, 'participantId': 3, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1560442
27,"[{'level': 13, 'participantId': 9, 'timestamp'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1620454
28,"[{'creatorId': 10, 'timestamp': 1621483, 'type...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1680455
29,"[{'itemId': 3211, 'participantId': 4, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1740479
30,"[{'levelUpType': 'NORMAL', 'participantId': 3,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1800481
31,"[{'creatorId': 10, 'timestamp': 1800647, 'type...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1860505
32,"[{'itemId': 3134, 'participantId': 7, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1920530
33,"[{'gameId': 6965278983, 'realTimestamp': 17088...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1927517

## 게임 시작 1분 안에 일어난 것들: timestamp 를 기준으로

In [344]:
# 게임 시작 1분 안에 일어난 이벤트 프레임 
pd.DataFrame(df3['events'][13])

,killerId,timestamp,type,wardType,itemId,participantId,creatorId,laneType,position,teamId,...,victimDamageReceived,victimId,afterId,beforeId,goldGain,level,buildingType,towerType,levelUpType,skillSlot
0,10.0,720329,WARD_KILL,UNDEFINED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,721733,ITEM_DESTROYED,NaN,2055.0,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,721733,WARD_PLACED,CONTROL_WARD,NaN,NaN,10.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,722634,ITEM_DESTROYED,NaN,6670.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,722634,ITEM_DESTROYED,NaN,1042.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,722634,ITEM_PURCHASED,NaN,6672.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6.0,724899,TURRET_PLATE_DESTROYED,NaN,NaN,NaN,NaN,TOP_LANE,"{'x': 981, 'y': 10441}",100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,725796,WARD_PLACED,TEEMO_MUSHROOM,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10.0,725996,WARD_KILL,SIGHT_WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,726530,ITEM_DESTROYED,NaN,2055.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,726530,WARD_PLACED,CONTROL_WARD,NaN,NaN,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,7.0,730658,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,"{'x': 6876, 'y': 6425}",NaN,...,"[{'basic': False, 'magicDamage': 162, 'name': ...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1.0,730658,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,"{'x': 7052, 'y': 6309}",NaN,...,"[{'basic': False, 'magicDamage': 0, 'name': 'T...",7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,734394,ITEM_PURCHASED,NaN,1026.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,736062,ITEM_DESTROYED,NaN,2422.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,736062,ITEM_PURCHASED,NaN,3020.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4.0,736392,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,"{'x': 13157, 'y': 2739}",NaN,...,"[{'basic': False, 'magicDamage': 65, 'name': '...",10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,739761,ITEM_DESTROYED,NaN,1052.0,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,739761,ITEM_PURCHASED,NaN,3113.0,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,741425,ITEM_PURCHASED,NaN,2055.0,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,741625,ITEM_DESTROYED,NaN,2422.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,741625,ITEM_PURCHASED,NaN,3047.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,743491,ITEM_DESTROYED,NaN,3866.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,744290,ITEM_PURCHASED,NaN,1036.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,744459,ITEM_PURCHASED,NaN,1028.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,745158,ITEM_PURCHASED,NaN,2055.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,745293,ITEM_PURCHASED,NaN,2055.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,747095,ITEM_UNDO,NaN,NaN,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,2055.0,75.0,NaN,NaN,NaN,NaN,NaN
28,NaN,747295,ITEM_DESTROYED,NaN,1028.0,8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,747295,ITEM_DESTROYED,NaN,1027.0,8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,747295,ITEM_PURCHASED,NaN,6657.0,8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,748130,WARD_PLACED,SIGHT_WARD,NaN,NaN,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,749234,ITEM_PURCHASED,NaN,3145.0,8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,749301,WARD_PLACED,SIGHT_WARD,NaN,NaN,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,751002,ITEM_PURCHASED,NaN,2055.0,8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,3.0,755777,WARD_KILL,CONTROL_WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,5.0,757240,WARD_KILL,CONTROL_WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,757240,LEVEL_UP,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
38,NaN,757240,WARD_PLACED,UNDEFINED,NaN,NaN,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,764834,LEVEL_UP,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
40,6.0,765873,TURRET_PLATE_DESTROYED,NaN,NaN,NaN,NaN,TOP_LANE,"{'x': 981, 'y': 10441}",100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,6.0,765873,BUILDING_KILL,NaN,NaN,NaN,NaN,TOP_LANE,"{'x': 981, 'y': 10441}",100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TOWER_BUILDING,OUTER_TURRET,NaN,NaN
42,NaN,766707,SKILL_LEVEL_UP,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,3.0
43,4.0,770573,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,"{'x': 13723, 'y': 5937}",NaN,...,"[{'basic': True, 'magicDamage': 0, 'name': 'SR...",9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,770573,LEVEL_UP,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
45,NaN,771477,SKILL_LEVEL_UP,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,1.0
46,NaN,771843,SKILL_LEVEL_UP,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,1.0
47,7.0,773872,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,"{'x': 13581, 'y': 6152}",NaN,...,"[{'basic': True, 'magicDamage': 0, 'name': 'SR...",4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,773872,LEVEL_UP,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN
49,NaN,775302,SKILL_LEVEL_UP,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,1.0
50,NaN,778524,ITEM_DESTROYED,NaN,2055.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,778524,WARD_PLACED,CONTROL_WARD,NaN,NaN,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
#게임 시작 1분 안에 일어난 사람들 프레임 
pd.DataFrame(df3['participantFrames'][1])

,1,2,3,4,5,6,7,8,9,10
championStats,"{'abilityHaste': 0, 'abilityPower': 27, 'armor...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 36, 'armor...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 9, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 9, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 18, 'armor..."
currentGold,0,0,0,0,0,0,0,0,0,0
damageStats,"{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp..."
goldPerSecond,0,0,0,0,30,0,0,0,0,30
jungleMinionsKilled,0,0,0,0,0,0,0,0,0,0
level,1,1,1,1,1,1,1,1,1,1
minionsKilled,0,0,0,0,0,0,0,0,0,0
participantId,1,2,3,4,5,6,7,8,9,10
position,"{'x': 3047, 'y': 7599}","{'x': 8420, 'y': 4749}","{'x': 5771, 'y': 6715}","{'x': 11600, 'y': 1288}","{'x': 5918, 'y': 1251}","{'x': 4665, 'y': 14032}","{'x': 11067, 'y': 6764}","{'x': 9172, 'y': 8534}","{'x': 11343, 'y': 6424}","{'x': 10442, 'y': 6300}"
timeEnemySpentControlled,0,0,0,0,0,0,0,0,0,0
totalGold,500,500,500,500,500,500,500,500,500,500
xp,0,0,0,0,0,0,0,0,0,0

In [19]:
#챔피언 stts 에 뭐가 있는 지 
df3['participantFrames'][1]['1'].keys()

dict_keys(['championStats', 'currentGold', 'damageStats', 'goldPerSecond', 'jungleMinionsKilled', 'level', 'minionsKilled', 'participantId', 'position', 'timeEnemySpentControlled', 'totalGold', 'xp'])

In [40]:
#15분에 첫번째 사람의 total gold 수 
df3['participantFrames'][15]['1']['totalGold']

4303

In [47]:
#15분에 첫번째 사람의 level 
df3['participantFrames'][15]['1']['xp']

5078

In [75]:
#게임 시작 2분 안에 일어난 이벤트 프레임 
pd.DataFrame(df3['events'][2])

,levelUpType,participantId,skillSlot,timestamp,type,level,creatorId,wardType
0,NORMAL,4.0,1.0,64984,SKILL_LEVEL_UP,NaN,NaN,NaN
1,NORMAL,9.0,2.0,77980,SKILL_LEVEL_UP,NaN,NaN,NaN
2,NORMAL,10.0,1.0,79208,SKILL_LEVEL_UP,NaN,NaN,NaN
3,NORMAL,8.0,1.0,86582,SKILL_LEVEL_UP,NaN,NaN,NaN
4,NORMAL,2.0,3.0,89515,SKILL_LEVEL_UP,NaN,NaN,NaN
5,NORMAL,5.0,3.0,94609,SKILL_LEVEL_UP,NaN,NaN,NaN
6,NORMAL,6.0,1.0,100818,SKILL_LEVEL_UP,NaN,NaN,NaN
7,NaN,2.0,NaN,106485,LEVEL_UP,2.0,NaN,NaN
8,NORMAL,2.0,2.0,109284,SKILL_LEVEL_UP,NaN,NaN,NaN
9,NaN,7.0,NaN,109350,LEVEL_UP,2.0,NaN,NaN
10,NORMAL,7.0,3.0,110086,SKILL_LEVEL_UP,NaN,NaN,NaN
11,NaN,NaN,NaN,113050,WARD_PLACED,NaN,8.0,YELLOW_TRINKET

## 챔피언 사망사건이 일어남
#### 특이한 일이 일어났으므로 딕셔너리가 있는 열을 확인해본다

In [337]:
# 게임 시작 3분 후에 일어난 일 
### 34 열에 챔피언 사망사건이 있었음 victimDamageDealt, victimDamageReceived 열 확인하기 
pd.DataFrame(df3['events'][3])

,itemId,participantId,timestamp,type,level,levelUpType,skillSlot,creatorId,wardType,assistingParticipantIds,...,killerId,position,shutdownBounty,victimDamageDealt,victimDamageReceived,victimId,killType,afterId,beforeId,goldGain
0,2003.0,5.0,124605,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,3.0,125938,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,3.0,127034,SKILL_LEVEL_UP,NaN,NORMAL,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,8.0,127301,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,8.0,130000,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,5.0,130902,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,4.0,130902,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,4.0,131903,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1.0,132600,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,1.0,133661,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,6.0,138897,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,6.0,140095,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2003.0,7.0,141789,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,9.0,145352,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,10.0,145352,LEVEL_UP,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,10.0,146117,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,146686,WARD_PLACED,NaN,NaN,NaN,4.0,YELLOW_TRINKET,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,9.0,149185,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,5.0,149486,SKILL_LEVEL_UP,NaN,NORMAL,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,7.0,149987,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,7.0,150985,SKILL_LEVEL_UP,NaN,NORMAL,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,2.0,152318,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2003.0,6.0,154784,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2003.0,10.0,154816,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2010.0,10.0,154950,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,3.0,156776,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,157577,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,[5],...,4.0,"{'x': 13936, 'y': 3959}",0.0,"[{'basic': False, 'magicDamage': 157, 'name': ...","[{'basic': True, 'magicDamage': 0, 'name': 'SR...",10.0,NaN,NaN,NaN,NaN
27,NaN,NaN,157577,CHAMPION_SPECIAL_KILL,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,"{'x': 13870, 'y': 3746}",NaN,NaN,NaN,NaN,KILL_FIRST_BLOOD,NaN,NaN,NaN
28,NaN,NaN,157841,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,[10],...,9.0,"{'x': 13877, 'y': 3719}",0.0,"[{'basic': False, 'magicDamage': 0, 'name': 'N...","[{'basic': True, 'magicDamage': 0, 'name': 'SR...",4.0,NaN,NaN,NaN,NaN
29,NaN,2.0,159378,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,1.0,159510,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,8.0,159942,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,1.0,160843,SKILL_LEVEL_UP,NaN,NORMAL,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,8.0,161579,SKILL_LEVEL_UP,NaN,NORMAL,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,3.0,162447,SKILL_LEVEL_UP,NaN,NORMAL,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,1001.0,4.0,163876,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,1001.0,10.0,164109,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,1042.0,4.0,164274,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,4.0,166640,ITEM_UNDO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1042.0,300.0
39,NaN,4.0,166740,ITEM_UNDO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1001.0,300.0
40,1036.0,4.0,167939,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,1036.0,4.0,168039,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2003.0,6.0,172838,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,5.0,178004,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,5.0,178875,SKILL_LEVEL_UP,NaN,NORMAL,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
#victimDamageReceived  안에 어떤 게 있나 확인 
pd.DataFrame(pd.DataFrame(df3['events'][3]).iloc[34]['victimDamageReceived'])

,basic,magicDamage,name,participantId,physicalDamage,spellName,spellSlot,trueDamage,type
0,False,0,Neeko,10,0,summonerdot,4,90,OTHER
1,True,0,Neeko,10,38,neekobasicattack,64,0,OTHER
2,False,67,Neeko,10,0,neekoq,0,0,OTHER
3,False,64,TwistedFate,9,0,pickacard,1,0,OTHER
4,True,0,TwistedFate,9,53,twistedfatebasicattack4,67,0,OTHER
5,True,0,TwistedFate,9,57,twistedfatebasicattack,64,0,OTHER
6,False,121,TwistedFate,9,0,cardmasterstack,2,0,OTHER
7,True,0,TwistedFate,9,57,twistedfatebasicattack2,65,0,OTHER
8,True,0,SRU_ChaosMinionRanged,0,9,sru_chaosminionrangedbasicattack,64,0,MINION
9,True,0,SRU_ChaosMinionRanged,0,18,sru_chaosminionrangedbasicattack2,65,0,MINION
10,False,59,Zac,7,0,zacq,0,0,OTHER
11,True,0,Zac,7,49,zacbasicattack,64,0,OTHER
12,False,0,Zac,7,0,zacw,1,0,OTHER
13,True,0,Zac,7,48,zacbasicattack2,65,0,OTHER

In [109]:
#victimDamageDealt
pd.DataFrame(pd.DataFrame(df3['events'][3]).iloc[34]['victimDamageDealt'])

,basic,magicDamage,name,participantId,physicalDamage,spellName,spellSlot,trueDamage,type
0,False,0,Lucian,9,83,lucianq,0,15,OTHER
1,True,0,Lucian,9,62,lucianpassive,63,0,OTHER
2,False,20,Lucian,9,0,lucianpassive,63,0,OTHER
3,False,20,Lucian,9,31,lucianpassiveattack,0,0,OTHER
4,True,0,Lucian,10,62,lucianpassive,63,0,OTHER
5,False,20,Lucian,10,0,lucianpassive,63,0,OTHER
6,False,0,Lucian,10,83,lucianq,0,9,OTHER
7,False,20,Lucian,10,31,lucianpassiveattack,0,0,OTHER
8,True,0,Lucian,10,62,lucianbasicattack2,65,0,OTHER

In [25]:
pd.DataFrame(df3['participantFrames'][3])

,1,2,3,4,5,6,7,8,9,10
championStats,"{'abilityHaste': 0, 'abilityPower': 27, 'armor...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 36, 'armor...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 9, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 9, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 18, 'armor..."
currentGold,353,413,384,23,276,332,504,458,786,367
damageStats,"{'magicDamageDone': 1905, 'magicDamageDoneToCh...","{'magicDamageDone': 2422, 'magicDamageDoneToCh...","{'magicDamageDone': 1900, 'magicDamageDoneToCh...","{'magicDamageDone': 216, 'magicDamageDoneToCha...","{'magicDamageDone': 606, 'magicDamageDoneToCha...","{'magicDamageDone': 40, 'magicDamageDoneToCham...","{'magicDamageDone': 2483, 'magicDamageDoneToCh...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 1239, 'magicDamageDoneToCh...","{'magicDamageDone': 1414, 'magicDamageDoneToCh..."
goldPerSecond,0,0,0,0,30,0,0,0,0,30
jungleMinionsKilled,0,12,0,0,0,0,12,0,0,0
level,3,2,3,2,2,3,3,3,2,2
minionsKilled,12,0,13,10,0,11,0,15,10,3
participantId,1,2,3,4,5,6,7,8,9,10
position,"{'x': 2240, 'y': 12427}","{'x': 3375, 'y': 8331}","{'x': 6233, 'y': 6739}","{'x': 13271, 'y': 3389}","{'x': 11472, 'y': 1390}","{'x': 2877, 'y': 13175}","{'x': 11795, 'y': 1557}","{'x': 7185, 'y': 6597}","{'x': 11532, 'y': 1951}","{'x': 12346, 'y': 2831}"
timeEnemySpentControlled,4155,78660,21589,0,17055,2001,10293,0,12614,4919
totalGold,853,913,884,873,776,832,1004,958,1286,867
xp,738,635,768,508,508,924,720,924,462,462

### 게임시작 4분 안에 많은 일들이 발생해버림 => 열이 42개

In [118]:
# 4분 안에 일어난 이벤트 프레임 
pd.DataFrame(df3['events'][4]).columns

Index(['level', 'participantId', 'timestamp', 'type', 'levelUpType',
       'skillSlot', 'assistingParticipantIds', 'bounty', 'killStreakLength',
       'killerId', 'position', 'shutdownBounty', 'victimDamageDealt',
       'victimDamageReceived', 'victimId', 'itemId', 'creatorId', 'wardType',
       'afterId', 'beforeId', 'goldGain'],
      dtype='object')

In [148]:
pd.DataFrame(df3['events'][4])

,level,participantId,timestamp,type,levelUpType,skillSlot,assistingParticipantIds,bounty,killStreakLength,killerId,...,shutdownBounty,victimDamageDealt,victimDamageReceived,victimId,itemId,creatorId,wardType,afterId,beforeId,goldGain
0,3.0,2.0,180052,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2.0,181217,SKILL_LEVEL_UP,NORMAL,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,182650,CHAMPION_KILL,NaN,NaN,[9],300.0,0.0,7.0,...,0.0,"[{'basic': False, 'magicDamage': 8, 'name': 'R...","[{'basic': False, 'magicDamage': 62, 'name': '...",5.0,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,5.0,185887,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2031.0,NaN,NaN,NaN,NaN,NaN
4,NaN,5.0,186221,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2055.0,NaN,NaN,NaN,NaN,NaN
5,NaN,5.0,187885,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3340.0,NaN,NaN,NaN,NaN,NaN
6,NaN,5.0,187885,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3364.0,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,189951,WARD_PLACED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,YELLOW_TRINKET,NaN,NaN,NaN
8,NaN,1.0,190789,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,NaN
9,NaN,5.0,191286,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2055.0,NaN,NaN,NaN,NaN,NaN
10,NaN,7.0,195660,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1028.0,NaN,NaN,NaN,NaN,NaN
11,NaN,7.0,195792,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1028.0,NaN,NaN,NaN,NaN,NaN
12,3.0,9.0,196661,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3.0,10.0,196661,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,7.0,197295,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3340.0,NaN,NaN,NaN,NaN,NaN
15,NaN,7.0,197295,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3364.0,NaN,NaN,NaN,NaN,NaN
16,4.0,8.0,197894,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,6.0,198462,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,NaN
18,NaN,10.0,198561,SKILL_LEVEL_UP,NORMAL,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,8.0,200660,SKILL_LEVEL_UP,NORMAL,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,4.0,3.0,203627,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,9.0,204795,SKILL_LEVEL_UP,NORMAL,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,3.0,207136,SKILL_LEVEL_UP,NORMAL,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3.0,4.0,208100,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,4.0,209001,SKILL_LEVEL_UP,NORMAL,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,1.0,209001,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,NaN
26,NaN,10.0,209233,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1052.0,NaN,NaN,NaN,NaN,NaN
27,NaN,9.0,209634,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2015.0,NaN,NaN,NaN,NaN,NaN
28,NaN,9.0,210036,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1036.0,NaN,NaN,NaN,NaN,NaN
29,NaN,10.0,210334,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2055.0,NaN,NaN,NaN,NaN,NaN
30,NaN,9.0,211234,ITEM_UNDO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1036.0,350.0
31,NaN,9.0,211832,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1001.0,NaN,NaN,NaN,NaN,NaN
32,4.0,6.0,214297,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,6.0,215097,SKILL_LEVEL_UP,NORMAL,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,4.0,1.0,218932,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,5.0,221998,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2055.0,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,221998,WARD_PLACED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.0,CONTROL_WARD,NaN,NaN,NaN
37,4.0,2.0,222898,LEVEL_UP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,2.0,226367,SKILL_LEVEL_UP,NORMAL,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,1.0,226599,SKILL_LEVEL_UP,NORMAL,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,3.0,227065,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,232571,WARD_PLACED,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,YELLOW_TRINKET,NaN,NaN,NaN

In [92]:
#게임 시작 5분 후에 일어난 일들 
pd.DataFrame(df3['events'][5])

,itemId,participantId,timestamp,type,level,creatorId,wardType,levelUpType,skillSlot,assistingParticipantIds,bounty,killStreakLength,killerId,position,shutdownBounty,victimDamageDealt,victimDamageReceived,victimId
0,2003.0,3.0,241747,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,5.0,245023,LEVEL_UP,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,245756,WARD_PLACED,NaN,10.0,YELLOW_TRINKET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003.0,7.0,245890,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,5.0,247087,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2010.0,3.0,248925,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010.0,3.0,254395,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,4.0,255161,LEVEL_UP,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,4.0,255899,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,8.0,261537,LEVEL_UP,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,8.0,262540,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,3.0,266773,LEVEL_UP,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,267040,WARD_PLACED,NaN,4.0,YELLOW_TRINKET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,3.0,268009,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,1.0,268645,LEVEL_UP,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,1.0,270746,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,279520,CHAMPION_KILL,NaN,NaN,NaN,NaN,NaN,[2],300.0,0.0,1.0,"{'x': 4215, 'y': 11754}",0.0,"[{'basic': False, 'magicDamage': 54, 'name': '...","[{'basic': False, 'magicDamage': 0, 'name': 'L...",7.0
17,1028.0,7.0,281949,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1028.0,7.0,281949,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,6660.0,7.0,281949,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,10.0,282684,LEVEL_UP,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,10.0,283549,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,9.0,285049,LEVEL_UP,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,9.0,285882,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1028.0,6.0,286480,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,6.0,295397,LEVEL_UP,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2003.0,4.0,296401,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,6.0,296999,SKILL_LEVEL_UP,NaN,NaN,NaN,NORMAL,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2010.0,10.0,297534,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2010.0,4.0,299600,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 데이터 프레임 한 행으로 만들기
### df_team_kill , df_monster , df_participant_KDA

In [ ]:
r1=requests.get('https://asia.api.riotgames.com/lol/match/v5/matches/KR_6965278983/timeline?api_key=RGAPI-c33dbe68-ba64-4996-8a8c-37c7cfd572a0')

In [ ]:
df2=pd.DataFrame(r1.json())

In [ ]:
df3=pd.DataFrame(df2['info']['frames'])

## df_team_kill: 블루팀과 레드팀의 퍼스트 블러드 여부
### 팀별 KDA

In [330]:
# 변수 초기화
blue_kill, red_kill = 0, 0
blue_firstkill, red_firstkill = 0, 0
blue_assist, red_assist = 0, 0
red_death, blue_death = 0, 0

for i in range(0, 16):
    # DataFrame으로 변환합니다.
    df = pd.DataFrame(df3['events'][i])
    # 'type' 열이 'CHAMPION_KILL'인 행들을 선택합니다.
    selected_champion_kills = df[df['type'] == 'CHAMPION_KILL']
    
    for index, event in selected_champion_kills.iterrows():
        # 킬러의 팀을 확인합니다.
        if event['killerId'] in range(1, 6):  # Blue Team
            if red_kill == 0 and blue_kill == 0:
                blue_firstkill += 1
            blue_kill += 1
            assist_ids = event['assistingParticipantIds']
            if isinstance(assist_ids, list):
                blue_assist += len(assist_ids)
            red_death += 1
        elif event['killerId'] in range(6, 11):  # Red Team
            if red_kill == 0 and blue_kill == 0:
                red_firstkill += 1
            red_kill += 1
            assist_ids = event['assistingParticipantIds']
            if isinstance(assist_ids, list):
                red_assist += len(assist_ids)
            blue_death += 1
            

# 결과 출력
print("Blue Team:")
print("Total Kills:", blue_kill)
print("First Kills:", blue_firstkill)
print("Total Assists:", blue_assist)
print("Red Team:")
print("Total Kills:", red_kill)
print("First Kills:", red_firstkill)
print("Total Assists:", red_assist)

# 각 팀의 킬 수를 담은 리스트 생성
blue_firstkill_list = [blue_firstkill]
red_firstkill_list = [red_firstkill]

# 데이터프레임 생성
df_team_kill = pd.DataFrame(data={'blue_firstkill': blue_firstkill_list, 'red_firstkill': red_firstkill_list})
df_team_kill

Blue Team:
Total Kills: 7
First Kills: 1
Total Assists: 5
Red Team:
Total Kills: 21
First Kills: 0
Total Assists: 22

   blue_firstkill  red_firstkill
0               1              0

## df_monster:드래곤, 퍼스트 드래곤, 호드 처치 수

In [324]:
# 변수 초기화
blue_elite, red_elite = 0, 0
blue_HORDE, red_HORDE = 0, 0
blue_dragon, red_dragon = 0, 0
blue_baron, red_baron = 0, 0
blue_firstdragon, red_firstdragon = 0, 0
blue_dragontype, red_dragontype = [], []

for i in range(0, 16):
    # DataFrame으로 변환합니다.
    df = pd.DataFrame(df3['events'][i])
    # 'type' 열이 'ELITE_MONSTER_KILL'인 행들을 선택합니다.
    selected_ELITE_MONSTER_KILL = df[df['type'] == 'ELITE_MONSTER_KILL']
    
    for index, event in selected_ELITE_MONSTER_KILL.iterrows():
        # 이벤트의 유형을 확인합니다.
        if event['monsterType'] == 'DRAGON':
            # 킬러의 팀을 확인합니다.
            if event['killerId'] in range(1, 6):  # Blue Team
                blue_dragon += 1
                if blue_dragon == 1 and red_dragon == 0:
                    blue_firstdragon += 1
                blue_dragontype.append(event['monsterSubType'])
            else:  # Red Team
                red_dragon += 1
                if red_dragon == 1 and blue_dragon == 0:
                    red_firstdragon += 1
                red_dragontype.append(event['monsterSubType'])
        elif event['monsterType'] == 'HORDE':
            if event['killerId'] in range(1, 6):  # Blue Team
                blue_HORDE += 1
            else:  # Red Team
                red_HORDE += 1
        elif event['monsterType'] == 'BARON_NASHOR':
            if event['killerId'] in range(1, 6):  # Blue Team
                blue_baron += 1
                if blue_baron == 1 and red_baron == 0:
                    blue_firstbaron += 1
            else:  # Red Team
                red_baron += 1
                if red_baron == 1 and blue_baron == 0:
                    red_firstbaron += 1
# 결과 출력
print("Blue Team:")
print("Total Dragon Kills:", blue_dragon)
print("First Dragon:", blue_firstdragon)
print("Dragon Types:", blue_dragontype)
print("Total Rift Herald Kills:", blue_HORDE)
print("Total Baron Kills:", blue_baron)
print("First Baron:", blue_firstbaron)

print("\nRed Team:")
print("Total Dragon Kills:", red_dragon)
print("First Dragon:", red_firstdragon)
print("Dragon Types:", red_dragontype)
print("Total Rift Herald Kills:", red_HORDE)
print("Total Baron Kills:", red_baron)
print("First Baron:", red_firstbaron)

Blue Team:
Total Dragon Kills: 0
First Dragon: 0
Dragon Types: []
Total Rift Herald Kills: 3
Total Baron Kills: 0
First Baron: 0

Red Team:
Total Dragon Kills: 2
First Dragon: 1
Dragon Types: ['WATER_DRAGON', 'HEXTECH_DRAGON']
Total Rift Herald Kills: 3
Total Baron Kills: 0
First Baron: 0

In [333]:
# 각 팀의 킬 수를 담은 리스트 생성
blue_dragon_list = [blue_dragon]
blue_firstdragon_list=[blue_firstdragon]
blue_HORDE_list=[blue_HORDE]
red_dragon_list = [red_dragon]
red_firstdragon_list=[red_firstdragon]
red_HORDE_list=[red_HORDE]


# 데이터 프레임 생성
df_monster = pd.DataFrame(data={'blue_dragon': blue_dragon_list,
                        'blue_firstdragon': blue_firstdragon_list,
                        'blue_HORDE': blue_HORDE_list,
                        'red_dragon': red_dragon_list,
                        'red_firstdragon': red_firstdragon_list,
                        'red_HORDE': red_HORDE_list})

# 결과 출력
df_monster

,blue_dragon,blue_firstdragon,blue_HORDE,red_dragon,red_firstdragon,red_HORDE
0,0,0,3,2,1,3

## df_participant_KDA: 개인별 KDA

In [302]:
# 변수 초기화
participant_stats = {}

for i in range(0, 16):
    # DataFrame으로 변환합니다.
    df = pd.DataFrame(df3['events'][i])
    # 'type' 열이 'CHAMPION_KILL'인 행들을 선택합니다.
    selected_champion_kills = df[df['type'] == 'CHAMPION_KILL']
    
    for index, event in selected_champion_kills.iterrows():
        killer_id = event['killerId']
        if killer_id not in participant_stats:
            participant_stats[killer_id] = {'kills': 0, 'assists': 0, 'deaths': 0}
        
        participant_stats[killer_id]['kills'] += 1
        
        assist_ids = event['assistingParticipantIds']
        if isinstance(assist_ids, list):
            participant_stats[killer_id]['assists'] += len(assist_ids)
        
        # 사망자도 킬 수에 포함되므로 사망 수도 증가시킵니다.
        death_ids = event['victimId']
        if death_ids not in participant_stats:
            participant_stats[death_ids] = {'kills': 0, 'assists': 0, 'deaths': 0}
        
        participant_stats[death_ids]['deaths'] += 1

# 결과 출력
for participant_id, stats in participant_stats.items():
    print(f"Participant {participant_id}: Kills={stats['kills']}, Assists={stats['assists']}, Deaths={stats['deaths']}")

Participant 4.0: Kills=6, Assists=5, Deaths=6
Participant 10.0: Kills=1, Assists=0, Deaths=4
Participant 9.0: Kills=4, Assists=7, Deaths=2
Participant 7.0: Kills=11, Assists=13, Deaths=1
Participant 1.0: Kills=1, Assists=0, Deaths=5
Participant 5.0: Kills=0, Assists=0, Deaths=3
Participant 8.0: Kills=2, Assists=1, Deaths=0
Participant 3.0: Kills=0, Assists=0, Deaths=3
Participant 6.0: Kills=3, Assists=1, Deaths=0
Participant 2.0: Kills=0, Assists=0, Deaths=4

In [335]:
# 데이터 프레임 안에 넣기 
participant_kills = {}
participant_assists = {}
participant_deaths={}


for participant_id, stats in participant_stats.items():
    participant_kills[f"participant{participant_id}_kill"] = stats['kills']
    participant_assists[f"participant{participant_id}_ass"] = stats['assists']
    participant_deaths[f"participant{participant_id}_deaths"] = stats['deaths']
    
df_kill = pd.DataFrame.from_dict(participant_kills, orient='index').T
df_assist=pd.DataFrame.from_dict(participant_assists, orient='index').T
df_deaths=pd.DataFrame.from_dict(participant_deaths, orient='index').T    


# 수평으로 데이터프레임 결합
df_participant_KDA = pd.concat([df_kill, df_assist, df_deaths], axis=1)
df_participant_KDA

,participant4.0_kill,participant10.0_kill,participant9.0_kill,participant7.0_kill,participant1.0_kill,participant5.0_kill,participant8.0_kill,participant3.0_kill,participant6.0_kill,participant2.0_kill,...,participant4.0_deaths,participant10.0_deaths,participant9.0_deaths,participant7.0_deaths,participant1.0_deaths,participant5.0_deaths,participant8.0_deaths,participant3.0_deaths,participant6.0_deaths,participant2.0_deaths
0,6,1,4,11,1,0,2,0,3,0,...,6,4,2,1,5,3,0,3,0,4

# 한 행짜리 데이터 프레임 최종

In [336]:
pd.concat([df_participant_KDA, df_monster, df_team_kill], axis=1)

,participant4.0_kill,participant10.0_kill,participant9.0_kill,participant7.0_kill,participant1.0_kill,participant5.0_kill,participant8.0_kill,participant3.0_kill,participant6.0_kill,participant2.0_kill,...,participant6.0_deaths,participant2.0_deaths,blue_dragon,blue_firstdragon,blue_HORDE,red_dragon,red_firstdragon,red_HORDE,blue_firstkill,red_firstkill
0,6,1,4,11,1,0,2,0,3,0,...,0,4,0,0,3,2,1,3,1,0