In [1]:
api_key = 'RGAPI-4daeecef-0878-494f-a05c-7c7e8eb77112'

In [2]:
matchids = [
    "KR_6965278983",
    "KR_6961163006",
    "KR_6990258458",
    "KR_6991192961",
    "KR_6987828402",
    "KR_6985798489",
    "KR_6948539783",
    "KR_6973961121",
    "KR_6957839106",
    "KR_6829343287",
    "KR_6959525589",
    "KR_6908234145",
    "KR_6932045276",
    "KR_6989800398",
    "KR_6973475765",
    "KR_6919176851",
    "KR_6930061690",
    "KR_6949132608",
    "KR_6986305074",
    "KR_6986870071",
    "KR_6749874938",
    "KR_6911108539",
    "KR_6949084426",
    "KR_6909149627",
    "KR_6968580712",
    "KR_6922604215",
    "KR_6878093211",
    "KR_6984544508",
    "KR_6945579261",
    "KR_6819224268",
    "KR_6981856644",
    "KR_6969246907",
    "KR_6820800743",
    "KR_6923836083",
    "KR_6549761285",
    "KR_6968826658",
    "KR_6935584432",
    "KR_6988134519",
    "KR_6779570345",
    "KR_6986595561",
    "KR_6956882874",
    "KR_6961319750",
    "KR_6617836335",
    "KR_6950995231",
    "KR_6904901662",
    "KR_6933789998",
    "KR_6979826555",
    "KR_6974661213",
    "KR_6835286023",
    "KR_6972524012",
    "KR_6986757531",
    "KR_6955408544",
    "KR_6943632875",
    "KR_6991574731",
    "KR_6937622325",
    "KR_6876659182",
    "KR_6988486047",
    "KR_6992134374",
    "KR_6884147693",
    "KR_6909662696",
    "KR_6964573772",
    "KR_6906346122",
    "KR_6966414205",
    "KR_6973575922",
    "KR_6898910291",
    "KR_5930648311",
    "KR_6993416240",
    "KR_6984504214",
    "KR_6946234275",
    "KR_6977994145",
    "KR_6977795569",
    "KR_6679988063",
    "KR_6971761823",
    "KR_6864462213",
    "KR_6994979352",
    "KR_6744630152",
    "KR_6857258674",
    "KR_6969134914",
    "KR_6978946197",
    "KR_6919967633",
    "KR_6981853288",
    "KR_6985934786",
    "KR_6780632372",
    "KR_6952224818",
    "KR_6912249500",
    "KR_6966531804",
    "KR_6937586411",
    "KR_6890146580",
    "KR_6986429061",
    "KR_6668597182",
    "KR_6981991029",
    "KR_6956877103",
    "KR_6964627471",
    "KR_6921339334",
    "KR_6973230618",
    "KR_6863114183",
    "KR_6980418077",
    "KR_6967213888",
    "KR_6961226279",
    "KR_6654208256"
]

In [3]:
import requests
import pandas as pd
import time

In [14]:
match15 = pd.DataFrame() ;match15

Empty DataFrame
Columns: []
Index: []

In [15]:
for i in range(len(matchids)):
    try:
        matchtime = 'https://asia.api.riotgames.com/lol/match/v5/matches/' + matchids[i] + '/timeline?api_key=' + api_key 
        r = requests.get(matchtime)
        match = 'https://asia.api.riotgames.com/lol/match/v5/matches/' + matchids[i] + '?api_key=' + api_key
        j = requests.get(match)
    
        while r.status_code == 429:
            time.sleep(5)
            matchtime = 'https://asia.api.riotgames.com/lol/match/v5/matches/' + matchids[i] + '/timeline?api_key=' + api_key 
            r = requests.get(matchtime)
            match = 'https://asia.api.riotgames.com/lol/match/v5/matches/' + matchids[i] + '?api_key=' + api_key
            j = requests.get(match)
        
        df_part = pd.DataFrame(j.json())
        participants_data = df_part['info']['participants']
        participants_df = pd.DataFrame(participants_data)
        df_time = pd.DataFrame(r.json())
        df_time = pd.DataFrame(df_time['info']['frames'])
        df_time15 = pd.DataFrame(df_time['participantFrames'][15])
    
       
        match15.loc[i,'matchid'] = matchids[i]
    
    ###############################################
    

        # match15 데이터프레임에 필요한 정보 추가
        # 챔피언 이름 할당
        for j in range(1, 6):
            match15.loc[i,f'championName_100_{j}'] = participants_df.loc[j-1, 'championName']
        for j in range(6, 11):
            match15.loc[i,f'championName_200_{j}'] = participants_df.loc[j-1, 'championName']
        #팀원 포지션 할당
        for j in range(1, 6):
            match15.loc[i,f'teamPosition_100_{j}'] = participants_df.loc[j-1, 'teamPosition']
        for j in range(6, 11):
            match15.loc[i,f'teamPosition_200_{j}'] = participants_df.loc[j-1, 'teamPosition']
        #소환사 별 15분 골드 할당
        for j in range(1, 6):
            match15.loc[i,f'totalGold_100_{j}'] = df_time15.iloc[10, j-1]
        for j in range(6, 11):
            match15.loc[i,f'totalGold_200_{j}'] = df_time15.iloc[10, j-1]
        #소환사 별 15분 레벨 할당 
        for j in range(1, 6):
            match15.loc[i,f'level_100_{j}'] = df_time15.iloc[5, j-1]
        for j in range(6, 11):
            match15.loc[i,f'level_200_{j}'] = df_time15.iloc[5, j-1]
        #소환사 별 15분 미니언 처치수 할당
        for j in range(1, 6):
            match15.loc[i,f'minionsKilled_100_{j}'] = df_time15.iloc[6, j-1]
        for j in range(6, 11):
            match15.loc[i,f'minionsKilled_200_{j}'] = df_time15.iloc[6, j-1]
        #소환사 별 15분 정글 미니언 처치수 할당 
        for j in range(1, 6):
            match15.loc[i,f'jungleMinionsKilled_100_{j}'] = df_time15.iloc[4, j-1]
        for j in range(6, 11):
            match15.loc[i,f'jungleMinionsKilled_200_{j}'] = df_time15.iloc[4, j-1]
             
        print(i, 'done')
        
    except Exception as e:
        print(i, f"Error occurred for matchid {matchids[i]}: {e}")
        pass

0 done
1 done
2 done
3 done
4 done
5 done
6 done
7 done
8 done
9 done
10 done
11 done
12 done
13 done
14 done
15 done
16 done
17 done
18 done
19 done
20 done
21 done
22 done
23 done
24 done
25 done
26 done
27 done
28 done
29 done
30 done
31 done
32 done
33 done
34 done
35 done
36 done
37 done
38 done
39 done
40 done
41 done
42 done
43 done
44 done
45 done
46 done
47 done
48 done
49 done
50 done
51 done
52 done
53 done
54 done
55 done
56 done
57 done
58 done
59 done
60 done
61 done
62 done
63 done
64 done
65 Error occurred for matchid KR_5930648311: 'info'
66 done
67 done
68 done
69 Error occurred for matchid KR_6977994145: 15
70 done
71 done
72 done
73 done
74 done
75 done
76 done
77 done
78 done
79 done
80 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
88 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done

In [16]:
match15

,matchid,championName_100_1,championName_100_2,championName_100_3,championName_100_4,championName_100_5,championName_200_6,championName_200_7,championName_200_8,championName_200_9,...,jungleMinionsKilled_100_1,jungleMinionsKilled_100_2,jungleMinionsKilled_100_3,jungleMinionsKilled_100_4,jungleMinionsKilled_100_5,jungleMinionsKilled_200_6,jungleMinionsKilled_200_7,jungleMinionsKilled_200_8,jungleMinionsKilled_200_9,jungleMinionsKilled_200_10
0,KR_6965278983,Teemo,Ekko,Tristana,Nilah,Maokai,Ryze,LeeSin,TwistedFate,Ezreal,...,2.0,92.0,0.0,0.0,0.0,4.0,70.0,0.0,0.0,0.0
1,KR_6961163006,Mordekaiser,Vi,Irelia,Smolder,Lux,Volibear,Ekko,Galio,Ezreal,...,0.0,76.0,0.0,0.0,0.0,0.0,84.0,0.0,0.0,0.0
2,KR_6990258458,XinZhao,Volibear,Ahri,Smolder,Braum,Kayle,Nocturne,AurelionSol,Jinx,...,0.0,76.0,0.0,0.0,0.0,0.0,80.0,0.0,0.0,0.0
3,KR_6991192961,KSante,Belveth,Annie,Lucian,Alistar,Riven,Nidalee,Malphite,Senna,...,0.0,102.0,0.0,0.0,0.0,0.0,94.0,0.0,0.0,4.0
4,KR_6987828402,Gangplank,Nidalee,Tristana,Varus,Lulu,Karma,MonkeyKing,Brand,Jinx,...,0.0,88.0,0.0,0.0,0.0,0.0,78.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,KR_6863114183,Aatrox,Belveth,Leblanc,Samira,Senna,Rumble,Graves,Talon,Nilah,...,0.0,70.0,0.0,0.0,0.0,0.0,84.0,0.0,0.0,0.0
96,KR_6980418077,TwistedFate,RekSai,Akshan,Ezreal,Lux,Nasus,Graves,Katarina,Jhin,...,0.0,82.0,1.0,0.0,0.0,0.0,76.0,0.0,0.0,0.0
97,KR_6967213888,Jax,Khazix,Sylas,Draven,Blitzcrank,Yorick,LeeSin,Akali,Ezreal,...,0.0,57.0,0.0,0.0,0.0,0.0,80.0,1.0,0.0,0.0
98,KR_6961226279,KSante,Khazix,Karma,Smolder,Lux,Aatrox,Nidalee,Zed,Varus,...,0.0,76.0,0.0,0.0,0.0,2.0,102.0,0.0,0.0,0.0
99,KR_6654208256,Renekton,Hecarim,Akali,Ezreal,Xerath,Fiora,Nocturne,Zilean,Zeri,...,0.0,112.0,0.0,0.0,0.0,0.0,80.0,0.0,0.0,0.0

In [17]:
match15.to_csv('/Users/hongminhwa/Desktop/match15.csv',index = False)